// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportJson(arg1, arg2) {
  return window['go']['internal']['Action']['ExportJson'](arg1, arg2);
}

export function FindRealWailsWindow() {
  return window['go']['internal']['Action']['FindRealWailsWindow']();
}

export function Hide() {
  return window['go']['internal']['Action']['Hide']();
}

export function ImportJson(arg1) {
  return window['go']['internal']['Action']['ImportJson'](arg1);
}

export function RecordActiveWindow() {
  return window['go']['internal']['Action']['RecordActiveWindow']();
}

export function RestoreFocus(arg1) {
  return window['go']['internal']['Action']['RestoreFocus'](arg1);
}

export function SendPaste() {
  return window['go']['internal']['Action']['SendPaste']();
}

export function SetSelfHwnd(arg1) {
  return window['go']['internal']['Action']['SetSelfHwnd'](arg1);
}

export function SetSizeNative(arg1, arg2) {
  return window['go']['internal']['Action']['SetSizeNative'](arg1, arg2);
}

export function SetTransparency(arg1) {
  return window['go']['internal']['Action']['SetTransparency'](arg1);
}

export function ShowNoActivate() {
  return window['go']['internal']['Action']['ShowNoActivate']();
}
