// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMousePosition() {
  return window['go']['internal']['Action']['GetMousePosition']();
}

export function RecordActiveWindow() {
  return window['go']['internal']['Action']['RecordActiveWindow']();
}

export function RestoreFocus(arg1) {
  return window['go']['internal']['Action']['RestoreFocus'](arg1);
}
