// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {win} from '../models';

export function FindRealWailsWindow():Promise<win.HWND>;

export function Hide():Promise<void>;

export function RecordActiveWindow():Promise<win.HWND>;

export function RestoreFocus(arg1:win.HWND):Promise<void>;

export function SetSelfHwnd(arg1:win.HWND):Promise<void>;

export function ShowNoActivate():Promise<void>;
