// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {win} from '../models';

export function ExportJson(arg1:Array<any>,arg2:context.Context):Promise<void>;

export function FindRealWailsWindow():Promise<win.HWND>;

export function Hide():Promise<void>;

export function RecordActiveWindow():Promise<win.HWND>;

export function RestoreFocus(arg1:win.HWND):Promise<void>;

export function SendPaste():Promise<void>;

export function SetSelfHwnd(arg1:win.HWND):Promise<void>;

export function SetSizeNative(arg1:number,arg2:number):Promise<void>;

export function SetTransparency(arg1:number):Promise<void>;

export function ShowNoActivate():Promise<void>;
