// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsAutoStartCheck():Promise<boolean>;

export function ToggleAutoStart(arg1:boolean):Promise<void>;
