// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsAutoStartCheck() {
  return window['go']['internal']['AppService']['IsAutoStartCheck']();
}

export function ToggleAutoStart(arg1) {
  return window['go']['internal']['AppService']['ToggleAutoStart'](arg1);
}
