// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterSettingsMode():Promise<void>;

export function ExitSettingsMode():Promise<void>;

export function GetContent():Promise<Array<any>>;

export function HideWindow():Promise<void>;

export function PasteAndHide():Promise<void>;

export function SaveContent(arg1:Array<any>):Promise<void>;

export function ToggleWindow():Promise<void>;
