// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterSettingsMode() {
  return window['go']['main']['App']['EnterSettingsMode']();
}

export function ExitSettingsMode() {
  return window['go']['main']['App']['ExitSettingsMode']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContent() {
  return window['go']['main']['App']['GetContent']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PasteAndHide() {
  return window['go']['main']['App']['PasteAndHide']();
}

export function RegisterGlobalHotkey(arg1, arg2) {
  return window['go']['main']['App']['RegisterGlobalHotkey'](arg1, arg2);
}

export function SaveContent(arg1) {
  return window['go']['main']['App']['SaveContent'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
