// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContent() {
  return window['go']['main']['App']['GetContent']();
}

export function SaveContent(arg1) {
  return window['go']['main']['App']['SaveContent'](arg1);
}
