// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function EnterSettingsMode():Promise<void>;

export function ExitSettingsMode():Promise<void>;

export function GetConfig():Promise<internal.Config>;

export function GetContent():Promise<Array<any>>;

export function HideWindow():Promise<void>;

export function PasteAndHide():Promise<void>;

export function RegisterGlobalHotkey(arg1:string,arg2:string):Promise<void>;

export function SaveContent(arg1:Array<any>):Promise<void>;

export function SetOpacity(arg1:number):Promise<void>;

export function ToggleWindow():Promise<void>;

export function UpdateConfig(arg1:internal.Config):Promise<string>;
