// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterSettingsMode() {
  return window['go']['main']['App']['EnterSettingsMode']();
}

export function ExitSettingsMode() {
  return window['go']['main']['App']['ExitSettingsMode']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContent() {
  return window['go']['main']['App']['GetContent']();
}

export function GetContextSlots() {
  return window['go']['main']['App']['GetContextSlots']();
}

export function GetContextSuggestions() {
  return window['go']['main']['App']['GetContextSuggestions']();
}

export function GetDataPath() {
  return window['go']['main']['App']['GetDataPath']();
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}

export function HideAndRestore() {
  return window['go']['main']['App']['HideAndRestore']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PasteAndHide() {
  return window['go']['main']['App']['PasteAndHide']();
}

export function PinSlot(arg1, arg2) {
  return window['go']['main']['App']['PinSlot'](arg1, arg2);
}

export function RecordItemUsage(arg1) {
  return window['go']['main']['App']['RecordItemUsage'](arg1);
}

export function RegisterGlobalHotkey(arg1, arg2) {
  return window['go']['main']['App']['RegisterGlobalHotkey'](arg1, arg2);
}

export function RemoveItemUsage(arg1) {
  return window['go']['main']['App']['RemoveItemUsage'](arg1);
}

export function SaveContent(arg1) {
  return window['go']['main']['App']['SaveContent'](arg1);
}

export function SetFontSizeLevel(arg1) {
  return window['go']['main']['App']['SetFontSizeLevel'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UnpinSlot(arg1) {
  return window['go']['main']['App']['UnpinSlot'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
